accounts/urls.py
from django.urls import path 

from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('user/', include('accounts.urls', namespace='accounts'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('product/<str:slug>', views.product_details, name="details"),
    path('product/type/<str:slug>', views.product_search_categories, name="cate_filter")
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.title


class Product(models.Model):
    class PRODUCT_TYPE(models.TextChoices):
        MOVIE = 'movies', 'Movie'
        BOOK = 'books', 'Book'

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_type = models.CharField(max_length=10, choices=PRODUCT_TYPE.choices)
    title = models.CharField(max_length=220)
    slug = models.SlugField(blank=True, null=True)
    image = models.ImageField(upload_to='product/')
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_average_rating(self):
        all_reviews = self.comment_set.all()
        all_rating = 0

        if len(all_reviews) > 0:
            for review in all_reviews:
                all_rating += int(review.rating)
            
            return round(all_rating / len(all_reviews), 2)
        return '-'

    def count_rating(self):
        all_reviews = self.comment_set.all()
        count = all_reviews.count()
        return count


def slugify_pre_save(sender, instance, *args, **kwargs):
    if instance.slug is None or instance.slug == '':
        new_slug = slugify(instance.title)
        klass = instance.__class__
        qs = klass.objects.filter(
            slug__icontains=new_slug).exclude(id=instance.id)
        if qs.count() == 0:
            instance.slug = new_slug
        else:
            instance.slug = f'{new_slug}-{qs.count()}'


pre_save.connect(slugify_pre_save, sender=Category)
pre_save.connect(slugify_pre_save, sender=Product)

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from .models import Category, Product
from comments.forms import CommentForm


def home(request):
    context = {}
    return render(request, 'home.html', context)


def search(request):
    categoires = Category.objects.all()
    products = Product.objects.all()
    products_count = products.count()

    page_title = 'Moives and Books'
    context = {
        'categoires': categoires,
        'products': products,
        'products_count': products_count,
        'page_title': page_title
    }
    return render(request, 'products/search.html', context)


def product_details(request, slug=None):
    product = get_object_or_404(Product, slug=slug)
    comments = product.comment_set.all()

    form = CommentForm(request.POST or None)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.user = request.user
        new_comment.product = product
        new_comment.save()
        return redirect(f"/product/{product.slug}")

    print(product.get_average_rating())

    context = {
        'product': product,
        'form': form,
        'comments': comments,
    }
    return render(request, 'products/details.html', context)


def product_search_categories(request, slug=None):
    products = Product.objects.filter(
        Q(product_type=slug) | Q(category__title=slug)
    )

    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query)
        )

    products_count = products.count()

    categoires = Category.objects.all()
    page_title = slug
    context = {
        'categoires': categoires,
        'products': products,
        'products_count': products_count,
        'page_title': page_title
    }
    return render(request, 'products/search.html', context)

templates/products/details.html
{% extends "../base.html" %}
{% block title %}{{product.title}}{% endblock %}
{% block content %}


<section class="bg-white dark:bg-gray-900">
    <div class="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
        <div class=" lg:mt-0 lg:col-span-3 lg:flex">
            <img src="{{product.image.url}}" alt="{{product.title}}">
        </div>                
        <div class=" lg:col-span-8">
            <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
                <h2 class="mb-2 text-3xl font-semibold leading-none text-blue-800 dark:text-white">{{product.title}}</h2>
                {% comment %} <p class="mb-4 text-xl font-extrabold leading-none text-gray-900 md:text-2xl dark:text-white">$2999</p> {% endcomment %}
                <dl class="mt-5">
                    <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Details</dt>
                    <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400">Standard glass ,3.8GHz 8-core 10th-generation Intel Core i7 processor, Turbo Boost up to 5.0GHz, 16GB 2666MHz DDR4 memory, Radeon Pro 5500 XT with 8GB of GDDR6 memory, 256GB SSD storage, Gigabit Ethernet, Magic Mouse 2, Magic Keyboard - US.</dd>
                </dl>
                <div class="flex items-center">
                    <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white mr-2">Rating</dt>
                    
                    <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                        <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                    </svg>
                    <p class="ml-2 text-sm font-bold text-gray-900 dark:text-white mr-1"> {{product.get_average_rating}} </p>
                    <a class="text-sm font-medium text-gray-900 dark:text-white"> ({{product.count_rating}})</a>
                    {% comment %} <div class="flex items-center">? {% endcomment %}
                    {% comment %} </div> {% endcomment %}


                </div>
                <br>
                <dl class="flex items-center space-x-6">
                    <div>
                        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Type</dt>
                        <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400">{{product.product_type|title}}</dd>
                    </div>
                    <div>
                        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Category</dt>
                        <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400">{{product.category}}</dd>
                    </div>
                </dl>
            </div>
        </div>
    </div>
</section>
<hr>
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-12">
        
        <h1 class="mb-4 text-3xl font-extrabold tracking-tight leading-none text-blue-900 md:text-3xl dark:text-white">Rating and Reviews ({{product.count_rating}})</h1>

        


        <div class="bg-white dark:bg-gray-900 py-2 lg:py-6  antialiased">
            <div class="mx-auto px-4">
                {% if user.is_authenticated %}

              <form method="POST" action='{% url "products:details" slug=product.slug %}'  class=" max-w-3xl mb-6">
                    {% csrf_token %}
                    <div >
                        <label for="comment" class="sr-only">Your comment</label>
                        {{form.comment}}
                    </div>
                    
                    
                    <label for="comment">Rating</label>
                    {{form.rating}}
                    
                    

                  <button type="submit"
                      class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">
                      Post comment
                  </button>
              </form>

              {% else %}
              <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                To Add Comment Please, <a href='{% url "accounts:login" %}' class="font-bold underline">Login</a>
              </div>
              {% endif %}


            {% for comment in comments %}
                <article class="p-6 mb-3 text-base bg-white border-b border-gray-200 dark:border-gray-700 dark:bg-gray-900 ">
                    <footer class="flex justify-between items-center mb-2">
                        <div class="flex items-center">
                            <p class="inline-flex items-center mr-3 text-md text-blue-700 dark:text-white font-semibold">{{comment.user.username}}</p>
                            <p class="text-sm text-gray-600 dark:text-gray-400 mr-1"><time pubdate datetime="2022-03-12"
                                    title="March 12th, 2022">{{comment.updated|date:"M d, Y"}} </time></p>
                            
                            <p class="text-sm text-gray-600 dark:text-gray-400 mr-1"><time pubdate datetime="2022-03-12"
                                    title="March 12th, 2022 mr-1">| {{comment.updated|timesince}}</time></p>
                            
                            <p class="text-sm text-gray-600 dark:text-gray-400">| 
                                <div class="ml-1 flex items-center">
                                <svg class="w-4 h-4 text-yellow-300 mr-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                {{comment.rating}}</p>
                            </div>
                        </div>
                        
                    </footer>
                    <p class="text-gray-500 dark:text-gray-400">{{comment.comment}}</p>
                    
                </article>
            {% endfor %}

              
            </div>
          </div>
        
    </div>
    
</section>

{% endblock %}

templates/products/search.html
{% extends "../base.html" %}
{% block title %}Search{% endblock %}
{% block content %}

<section class="bg-white dark:bg-gray-900">
    <div class="grid  px-4 py-8 mx-auto  lg:grid-cols-12">
        <div class="lg:col-span-3 p-5">
            <div class="border p-3">
                <div class="py-2">
                    <h1 class="text-center text-3xl font-bold mb-3 text-blue-700">Filter</h1>
                </div>
                <form method="GET" action="{% url "products:cate_filter" slug="Search Results" %}">
                    <label for="simple-search" class="sr-only">Search</label>
                    <div class="relative w-full">
                      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                        </svg>
                      </div>
                      <input type="text" name='q' id="simple-search" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Search" required="">
                    </div>
                  </form>
                  <div class="mt-5">
                    <hr>
                    <div class=" mt-5 mb-5">
                        
                    <span class="flex items-center text-2xl text-bold mt-5 text-blue-700">
                        <span class="ml-2">Type:</span>
                    </span>
                    <ul class="space-y-2 pt-2 pl-5">
                        <li class="text-black-900 font-bold">
                            <a href="{% url "products:search" %}">

                                {% if page_title != 'Moives and Books' %}
                                - All 
                                {% else %}
                                    <span class="text-blue-600">- All</span>
                                {% endif %}
                            </a>
                        </li>
                        <li class="text-black-900 font-bold">
                            <a href="{% url "products:cate_filter" slug='movies' %}">
                                {% if page_title != 'movies' %}
                                - Movies 
                                {% else %}
                                    <span class="text-blue-600">- Movies</span>
                                {% endif %}
                            </a>
                        </li>
                        <li class="text-black-900 font-bold">
                            <a href="{% url "products:cate_filter" slug='books' %}">
                                {% if page_title != 'books' %}
                                - Books 
                                {% else %}
                                    <span class="text-blue-600">- Books</span>
                                {% endif %}
                            </a>
                        </li>
                    </ul>
                    </div>
                    <hr>
                    <div class=" mt-5">
                        
                    <span class="flex items-center text-2xl text-bold mt-5 text-blue-700">
                        <span class="ml-2">Categoires:</span>
                    </span>
                    <ul class="space-y-2 pt-2 pl-5">
                        {% for categore in categoires %}
                        <li class="text-black-900 font-bold">
                           <a href="{% url "products:cate_filter" slug=categore.title %}">
                            {% if categore.title != page_title %}
                            
                            - {{categore.title}}
                            
                            {% else %}
                            <span class="text-blue-600">- {{categore.title}}</span>
                            {% endif %}
                           </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                </div>
            </div>
            {% comment %} dasasasasasasasas asd a;kj  jk;ladskl;j lk;jasd {% endcomment %}
        </div>
        <div class="lg:col-span-8 p-5">
            <div class="bg-gray-50 dark:bg-gray-900">
                <!-- Start coding here -->
                <div class="relative overflow-hidden bg-white shadow-md dark:bg-gray-800 sm:rounded-lg">
                <div class="flex-row items-center justify-between p-4 space-y-3 sm:flex sm:space-y-0 sm:space-x-4">
                    <div>
                    <h5 class="text-xl text-blue-800 mr-3 font-semibold dark:text-white">
                        {% comment %} {% if page_title == 'None' %}
                            Search Results
                        {% else %}
                        {{page_title|title}}
                        
                        {% endif %} {% endcomment %}
                        {{page_title|title}}
                    
                    </h5>
                    </div>
                    Total ({{products_count}})
                </div>
                </div>
        </div>                
        <section class="container bg-white dark:bg-gray-900">
            <div class="py-8 px-4 ">    
                <div class="space-y-8 lg:grid lg:grid-cols-3 sm:gap-6 xl:gap-10 lg:space-y-0">
                    <!-- Pricing Card -->
                    {% for product in products %}
                    <div class=" w-full pb-7 max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                        <a href="{% url "products:details" slug=product.slug %}">
                            <img class="rounded text-center p-8 rounded-t-lg max-w-50" src="{{product.image.url}}" alt="{{product.title}}" style="width: 100%;height: 300px;object-fit: cover;" />
                        </a>
                        <div class="px-5 pb-5">
                            <a href="{% url "products:details" slug=product.slug %}" >
                                <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{product.title}}</h5>
                            </a>
                            <div class="flex ">
                                <svg class="w-4 h-4 text-yellow-300 mr-1 mt-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                {{product.get_average_rating}} ({{product.count_rating}})
                            </div> 
                            <div class="flex items-center mt-2.5 mb-5 py-2">
                                <span class="bg-green-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 m-1">{{product.product_type|title}}</span>
                                <span class="bg-cyan-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ">{{product.category}}</span>
                                
                            </div>
                            
                        </div>
                        <div class="w-full text-center">
                            <a href="{% url "products:details" slug=product.slug %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">More Details</a>
                        </div>
                    </div>
                    {% endfor %} 

</section>
                </div>
            </div>
          </section>
    </div>
</section>

{% endblock %}