accounts/urls.py
from django.urls import path 

from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('user/', include('accounts.urls', namespace='accounts'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('product/<str:slug>', views.product_details, name="details"),
    path('product/type/<str:slug>', views.product_search_categories, name="cate_filter")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookScreen Insights | {% block title %}{% endblock title %}</title>
    {% comment %} <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.css" rel="stylesheet" /> {% endcomment %}
    <link href="{% static "style/tailwind_output.css" %}" rel="stylesheet" />

</head>
<body>
        <header class="container antialiased">
            <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
                <div class="flex flex-wrap justify-between items-center">

                    <div class="flex justify-start items-center">
                        
                        <a href="\" class="flex mr-4">
                        <span class="self-center lg:text-2xl text-xl font-semibold text-blue-800 dark:text-white ms:mr-6">BookScreen Insights</span>
                        </a>
                        <form action="{% url "products:cate_filter" slug="Search Results" %}" method="GET" class="hidden lg:block lg:pl-2">
                        <label for="topbar-search" class="sr-only">Search</label>
                        <div class="relative mt-1 lg:w-96">
                            <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20"> <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/> </svg>
                            </div>
                            <input type="text" name="q" id="topbar-search" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-9 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search">
                        </div>
                        </form>
                    </div>

                    <div class="flex items-center lg:order-2">
                        {% if user.is_authenticated  %}
                            <button type="button" class="flex mx-3 bg-blue-100 text-md px-4 py-2 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="dropdown">
                                <p class="text-blue-600  font-bold ">{{user.username|title}}</p>
                                <span class="sr-only">Open user menu</span>
                                {% comment %} <img class="w-8 h-8 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-5.jpg" alt="user photo"> {% endcomment %}
                            </button>
                            <!-- Dropdown menu -->
                            <div class="hidden z-50 my-4 w-56 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown">
                                <div class="py-3 px-4">
                                    <span class="block text-sm font-semibold text-gray-900 dark:text-white">{{user.first_name|title}} {{user.last_name|title}}</span>
                                    <span class="block text-sm text-gray-500 truncate dark:text-gray-400">{{user.email}}</span>
                                </div>
                                <ul class="py-1 text-gray-500 dark:text-gray-400" aria-labelledby="dropdown">
                                    <li>
                                        <a class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">Username: {{user.username}}</a>
                                    </li>
                                    
                                </ul>
                                
                                <ul class="py-1 text-gray-500 dark:text-gray-400" aria-labelledby="dropdown">
                                    <li>
                                        <a href="{% url "accounts:logout" %}" class="block py-2 px-4 text-red-700 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Sign out</a>
                                    </li>
                                </ul>
                            </div>
                        {% else %}
                        
                            <a href="{% url 'accounts:login' %}" class="lg:mt-0 mt-3 sm:inline-flex items-center justify-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-xs px-5 py-2 mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"> Login</a>
                            
                            <a href="{% url 'accounts:register' %}" class="lg:mt-0 mt-3 sm:inline-flex items-center justify-center text-white bg-blue-800 hover:bg-blue-900 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-xs px-5 py-2 mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"> Sign UP</a>
                        

                       {% endif %}



                    </div>
                </div>
            </nav>
        </header>
        
    
    
    <div class="container mx-auto mt-4 min-h-screen">
        {% block content %}

        {% endblock content %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js"></script>
</body>
</html>

templates/home.html
{% extends './base.html' %}
{% load static %}
{% block title %}Movie Book Management{% endblock %}
{% block content %}

    <section class="bg-white dark:bg-gray-900">
        <div class="gap-16 items-center py-8 px-4 mx-auto max-w-screen-xl lg:grid lg:grid-cols-2 lg:py-16 lg:px-6">
            <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
                <h2 class="mb-4 text-5xl tracking-tight font-extrabold text-blue-800 dark:text-white">Your Path To All Movies And Books.</h2>
                <p class="mb-10">We are strategists, designers and developers. Innovators and problem solvers. Small enough to be simple and quick, but big enough to deliver the scope you want at the pace you need. Small enough to be simple and quick, but big enough to deliver the scope you want at the pace you need.</p>
                <p>We are strategists, designers and developers. Innovators and problem solvers. Small enough to be simple and quick.</p>
                <br>
                <br>
                
                <a href="{% url "products:search" %}" class="text-xl text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-900 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Get Started</a>
            </div>
            <div class="grid grid-cols-2 gap-4 mt-8">
                <img class="w-full rounded-lg" src="{% static 'images/av.jpg' %}" alt="office content 1">
                <img class="mt-4 w-full lg:mt-10 rounded-lg" src="{% static 'images/7hab.jpg' %}" alt="office content 2">
            </div>
        </div>

    </section>

{% endblock %}